### ISSUE TITLE
error: json: cannot unmarshal number into Go struct field repoSearch.project_public of type bool

### ISSUE THREAD

**Issue by learn0208** [moooofly/harbor-go-client#5] opened 2018-08-13 07:52 UTC
> # harbor-go-client rp_tags -d 30 -m 10
> ===============================
> ==  Start tags RP Analysing  ==
> ===============================
> 
> --------------------
> ==> GET https://harbor-host/api/search?q=
> error: json: cannot unmarshal number into Go struct field repoSearch.project_public of type bool

harbor version: harbor-v1.1.1
go version: go version go1.10.3 linux/amd64

When I run rp_tags command, I was got this error.
How can fix this error

**Comment by moooofly** [comment] 2018-08-13 11:14
Duplicate of https://github.com/moooofly/harbor-go-client/issues/2

I will close this one. Thanks.

**Closed** 2018-08-13 11:14 UTC
